config/routes.rb
Rails.application.routes.draw do
 

  root 'home#top'
  
  get '/home/about' => 'home#about',as:'about_note'
  get '/note' => 'notes#new',as:'new_note'
  post '/notes' => 'notes#create'
  
  get '/note/index' => 'notes#index',as:'index_note'
  get '/note/:id/show' => 'notes#show',as:'show_note'
  get'/note/:id/edit' => 'notes#edit',as:'edit_note'
  patch'/note/:id/' =>'notes#update',as:'update_note'
  delete'/note/:id/' => 'notes#destroy',as:'destroy_note'

end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end
  
  def show
    @note = Note.find(params[:id])
  end
  
  def new
    @note = Note.new
  end
  
  def create
    @note = Note.create(params_create)
    redirect_to note_index_path
  end
  
  def edit
    @note = Note.find(params[:id])
  end
  
    def update
      @note = Note.find(params[:id])
      @note.title = params[:title]
      @note.content = params[:content]
      @note.save
      redirect_to index_note_path(@note.id)
    end
  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to index_note_path
  end

  
  private
  
  def params_create
    params.require(:note).permit(:title,:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/about.html.erb
<h1>このサイトはテストのサイトです</h1>

app/views/home/top.html.erb
<div class="header">
  <div class="header-left">
    <h1>gatebookへようこそ</h1>
  </div>
  <div class="header-right">
    <li><%= link_to"new",new_note_path %></li>
    <li><%= link_to"index",index_note_path %></li>
    <li><%= link_to"about",about_note_path %></li>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gatebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<p><%= link_to"top",root_path %></p>
</body>
</html>

app/views/notes/edit.html.erb
<%= form_tag update_note_path(@note.id),method:'patch' do %>
<%= text_field_tag :title,@note.title %>
<%= text_area_tag :content,@note.content %>
<%= submit_tag '保存' %>
<% end %>

app/views/notes/index.html.erb
<h1>投稿一覧</h1>
<% @notes.each do |note| %>
<%= link_to note.title,show_note_path(note.id) %>

<% end %>

app/views/notes/new.html.erb
<h1>新規投稿ページ</h1>

<%= form_for @note do |f| %>
<%= f.text_field :title %>
<%= f.text_area :content %>
<%= f.submit "送信" %>
<% end %>

app/views/notes/show.html.erb
<h1>詳細ページ</h1>
<%= @note.title %>
<%= @note.content %>
<%= link_to'編集',edit_note_path(@note.id) %>
<%= link_to'削除',destroy_note_path(@note.id),method:'delete' %>